### ISSUE TITLE
start() does not wait for ES to be ready to receive queries

### ISSUE THREAD

**Issue by vojtapol** [allegro/embedded-elasticsearch#40]
Tested with Elasticsearch version `5.1.2` and `5.2`, EmbeddedElastic version `2.4.2`

Often (70% of runs) the first query from my application to Elasticsearch throws:
```
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{Cw1RyBb1SdiYFj7v7RxZbg}{127.0.0.1}{127.0.0.1:9350}]
```

I see that you wait for Elasticsearch to start by parsing the log but I believe it might be insufficient. My issue was fixed by adding:

```
while (true) {
    try {
        client.admin().cluster().prepareHealth().get()      // could be any other query
        break
    } catch (e: NoNodeAvailableException) {
        Thread.sleep(500)
        continue
    }
}
```

Right after the `start()` call. Now the queries are executed reliably with no exceptions. It's in the while loop for something between 500 - 1500 ms.

**Comment by gaczm** [comment]
Hi @vojtapol I've just pushed version in which I'm added waiting for yellow status after starting cluster and before executing any requests to it. I think it should help with your problem :)

**Comment by vojtapol** [comment]
I tested `2.4.4` and it indeed seems like the issues has been fixed. Thank you.

**Comment by vojtapol** [comment]
Never mind, I spoke too soon. It still happens. I guess waiting for yellow status is not the same as waiting for nodes responding to requests. To me it seems like a bug in ES.
